version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment: 
      MONGODB_URI: mongodb://mongo:27017/pets

  mongo:
    image: mongo
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

volumes:
  db:
