name: DeployWorkflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    container: bozdoz/fabric-deployment
    runs-on: ubuntu-latest
    steps:
      - run: fab gitpull dockercomposebuild
